### ISSUE TITLE
Fix mixit demo

### ISSUE THREAD

**Issue by acmiyaguchi** [dsgt-birdclef/birdclef-eda-f22#22]
If you go to the website and click on the mixit demo at the bottom of the page, it doesn't redirect to the right page: https://dsgt-birdclef.github.io/birdclef-eda-f22/

The build needs to be fixed to support it.

```bash
ReferenceError: fetch is not defined
    at module.exports (/home/runner/work/birdclef-eda-f22/birdclef-eda-f22/site/_data/mixit.js:5:17)
    at TemplateData.getDataValue (/home/runner/work/birdclef-eda-f22/birdclef-eda-f22/site/node_modules/@11ty/eleventy/src/TemplateData.js:511:29)
    at TemplateData.getAllGlobalData (/home/runner/work/birdclef-eda-f22/birdclef-eda-f22/site/node_modules/@11ty/eleventy/src/TemplateData.js:278:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TemplateData.getData (/home/runner/work/birdclef-eda-f22/birdclef-eda-f22/site/node_modules/@11ty/eleventy/src/TemplateData.js:327:24)
```

**Comment by acmiyaguchi** [comment]
Fixed, you can see https://dsgt-birdclef.github.io/birdclef-eda-f22/shared/mixit/ now
